# -*- coding: utf-8 -*-

# retired template keywords list
retired_template_list = [
    'visszavonult', 
    'lämnat', 
    '永遠離開', 
    'utilizator retras', 
    'کاربر بازنشسته', 
    'vertrokken', 
    'অবসরপ্রাপ্ত', 
    'retraité', 
    'pasitraukęs', 
    'պաշտոնաթող', 
    'විශ් රාමික', 
    'повлечен корисник', 
    'سبک دوش', 
    'emekli', 
    'deaktiviert', 
    'pènsiyun', 
    'పూర్తి విరమణ', 
    'usuário inativo', 
    'qeyri-aktiv', 
    'சுயவிடுப்பு', 
    'đã nghỉ việc', 
    'متقاعد', 'retired', 
    'usuario retirado', 
    'utente ritirato', 
    'เกษียณ', 'neaktiven', 
    'retirado', 
    '위키백과탈퇴', 
    'خانەنشین', 
    'jo aktiv', 
    'неактивен потребител'
]

# ban template words list
banned_template_list = [
    'bloccoinfinito', 
    'uw-botuhblock', 
    'uw-adminuhblock', 
    'uw-uhblock-double', 
    'user expelled', 
    'sockpuppet bloccato', 
    'títere', 
    'blocked impersonator', 
    'sockmasterproven', 
    'arbcomblock', 
    'uw-vaublock', 
    'uw-upeblock', 
    'uw-nothereblock', 
    'wmf-legal banned user', 
    'uw-blockindef', 
    'uw-acpblockindef', 
    'sspblock', 
    'sockblock', 
    'uw-pblockindef', 
    'uw-uhblock', 
    'banned user', 
    'uw-cabalblock', 
    'vandalo recidivo'
]